# Список запрещённых слов в чате
banned_words:
  - дурак
  - козёл
  - козел

# Команда для бана нарушителя
ban_command: "ban {player} Нарушение правил: плохие слова в чате"

# Включение/выключение выполнения дополнительной команды
additional_command_enabled: true

# Дополнительная команда (например, для уведомления администрации)
additional_command: "Игрок {player} был забанен за использование запрещённых слов в чате"
