name: ChatBan
version: '${project.version}'
main: org.xnbo.chatban.ChatBan
author: XINBOSHIN
api-version: '1.16'
commands:
  chatbanreload:
    description: Reloads the ChatBan plugin configuration
    usage: /chatbanreload